export * from './data'
export { default as Clients } from './Clients'
export { default as FAQs } from './FAQs'
export { default as Features } from './Features'
export { default as Footer } from './Footer'
export { default as PricingCards } from './PricingCards'
export { default as Testimonial } from './Testimonial'
export { default as Navbar2 } from './Navbar2'
export { default as Footer2 } from './Footer2'
export { default as Footer3 } from './Footer3'
export { default as Footer4 } from './Footer4'
export { default as PricingCards2 } from './PricingCards2'
